// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_realmlp_train
List rcpp_realmlp_train(NumericMatrix x_train, NumericVector y_train, Nullable<NumericMatrix> x_val, Nullable<NumericVector> y_val, std::string task, int n_epochs, int batch_size, double lr, int early_stopping_rounds, int seed, int verbose, int num_classes);
RcppExport SEXP _evoFE_rcpp_realmlp_train(SEXP x_trainSEXP, SEXP y_trainSEXP, SEXP x_valSEXP, SEXP y_valSEXP, SEXP taskSEXP, SEXP n_epochsSEXP, SEXP batch_sizeSEXP, SEXP lrSEXP, SEXP early_stopping_roundsSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP num_classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type x_val(x_valSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type y_val(y_valSEXP);
    Rcpp::traits::input_parameter< std::string >::type task(taskSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type early_stopping_rounds(early_stopping_roundsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type num_classes(num_classesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_realmlp_train(x_train, y_train, x_val, y_val, task, n_epochs, batch_size, lr, early_stopping_rounds, seed, verbose, num_classes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_realmlp_predict
NumericMatrix rcpp_realmlp_predict(List model_state, NumericMatrix x_new);
RcppExport SEXP _evoFE_rcpp_realmlp_predict(SEXP model_stateSEXP, SEXP x_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model_state(model_stateSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_new(x_newSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_realmlp_predict(model_state, x_new));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_evoFE_rcpp_realmlp_train", (DL_FUNC) &_evoFE_rcpp_realmlp_train, 12},
    {"_evoFE_rcpp_realmlp_predict", (DL_FUNC) &_evoFE_rcpp_realmlp_predict, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_evoFE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
