// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_compute_ts_refinement_binary
double rcpp_compute_ts_refinement_binary(NumericVector y_true, NumericVector y_pred, double alpha, bool is_logits, int threads);
RcppExport SEXP _evoFE_rcpp_compute_ts_refinement_binary(SEXP y_trueSEXP, SEXP y_predSEXP, SEXP alphaSEXP, SEXP is_logitsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_true(y_trueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_pred(y_predSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type is_logits(is_logitsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_ts_refinement_binary(y_true, y_pred, alpha, is_logits, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_ts_refinement_multiclass
double rcpp_compute_ts_refinement_multiclass(IntegerVector y_true, NumericMatrix y_pred, int num_class, double alpha, bool is_logits, int threads);
RcppExport SEXP _evoFE_rcpp_compute_ts_refinement_multiclass(SEXP y_trueSEXP, SEXP y_predSEXP, SEXP num_classSEXP, SEXP alphaSEXP, SEXP is_logitsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y_true(y_trueSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y_pred(y_predSEXP);
    Rcpp::traits::input_parameter< int >::type num_class(num_classSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type is_logits(is_logitsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_ts_refinement_multiclass(y_true, y_pred, num_class, alpha, is_logits, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_realmlp_train
List rcpp_realmlp_train(NumericMatrix x_train, NumericVector y_train, Nullable<NumericMatrix> x_val, Nullable<NumericVector> y_val, std::string task, int n_epochs, int batch_size, double lr, int early_stopping_rounds, int seed, int verbose, int num_classes, int threads, std::string metric, int hidden_dim);
RcppExport SEXP _evoFE_rcpp_realmlp_train(SEXP x_trainSEXP, SEXP y_trainSEXP, SEXP x_valSEXP, SEXP y_valSEXP, SEXP taskSEXP, SEXP n_epochsSEXP, SEXP batch_sizeSEXP, SEXP lrSEXP, SEXP early_stopping_roundsSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP num_classesSEXP, SEXP threadsSEXP, SEXP metricSEXP, SEXP hidden_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type x_val(x_valSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type y_val(y_valSEXP);
    Rcpp::traits::input_parameter< std::string >::type task(taskSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type early_stopping_rounds(early_stopping_roundsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type num_classes(num_classesSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< int >::type hidden_dim(hidden_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_realmlp_train(x_train, y_train, x_val, y_val, task, n_epochs, batch_size, lr, early_stopping_rounds, seed, verbose, num_classes, threads, metric, hidden_dim));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_realmlp_predict
NumericMatrix rcpp_realmlp_predict(List model_state, NumericMatrix x_new);
RcppExport SEXP _evoFE_rcpp_realmlp_predict(SEXP model_stateSEXP, SEXP x_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model_state(model_stateSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_new(x_newSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_realmlp_predict(model_state, x_new));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fused_row_min
NumericVector rcpp_fused_row_min(List cols, int threads);
RcppExport SEXP _evoFE_rcpp_fused_row_min(SEXP colsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fused_row_min(cols, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fused_row_max
NumericVector rcpp_fused_row_max(List cols, int threads);
RcppExport SEXP _evoFE_rcpp_fused_row_max(SEXP colsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fused_row_max(cols, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fused_geometric_mean
NumericVector rcpp_fused_geometric_mean(List cols, double eps, int threads);
RcppExport SEXP _evoFE_rcpp_fused_geometric_mean(SEXP colsSEXP, SEXP epsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fused_geometric_mean(cols, eps, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fused_harmonic_mean
NumericVector rcpp_fused_harmonic_mean(List cols, double eps, int threads);
RcppExport SEXP _evoFE_rcpp_fused_harmonic_mean(SEXP colsSEXP, SEXP epsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fused_harmonic_mean(cols, eps, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fused_pythagorean_imbalance
NumericVector rcpp_fused_pythagorean_imbalance(List cols, double eps, int threads);
RcppExport SEXP _evoFE_rcpp_fused_pythagorean_imbalance(SEXP colsSEXP, SEXP epsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fused_pythagorean_imbalance(cols, eps, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fused_relative_rating
NumericVector rcpp_fused_relative_rating(List cols, int threads);
RcppExport SEXP _evoFE_rcpp_fused_relative_rating(SEXP colsSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fused_relative_rating(cols, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_evoFE_rcpp_compute_ts_refinement_binary", (DL_FUNC) &_evoFE_rcpp_compute_ts_refinement_binary, 5},
    {"_evoFE_rcpp_compute_ts_refinement_multiclass", (DL_FUNC) &_evoFE_rcpp_compute_ts_refinement_multiclass, 6},
    {"_evoFE_rcpp_realmlp_train", (DL_FUNC) &_evoFE_rcpp_realmlp_train, 15},
    {"_evoFE_rcpp_realmlp_predict", (DL_FUNC) &_evoFE_rcpp_realmlp_predict, 2},
    {"_evoFE_rcpp_fused_row_min", (DL_FUNC) &_evoFE_rcpp_fused_row_min, 2},
    {"_evoFE_rcpp_fused_row_max", (DL_FUNC) &_evoFE_rcpp_fused_row_max, 2},
    {"_evoFE_rcpp_fused_geometric_mean", (DL_FUNC) &_evoFE_rcpp_fused_geometric_mean, 3},
    {"_evoFE_rcpp_fused_harmonic_mean", (DL_FUNC) &_evoFE_rcpp_fused_harmonic_mean, 3},
    {"_evoFE_rcpp_fused_pythagorean_imbalance", (DL_FUNC) &_evoFE_rcpp_fused_pythagorean_imbalance, 3},
    {"_evoFE_rcpp_fused_relative_rating", (DL_FUNC) &_evoFE_rcpp_fused_relative_rating, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_evoFE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
