# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast C++ Temperature-Scaled Refinement for Binary Classification
#' @keywords internal
rcpp_compute_ts_refinement_binary <- function(y_true, y_pred, alpha = 1.0, is_logits = FALSE, threads = 1L) {
    .Call(`_evoFE_rcpp_compute_ts_refinement_binary`, y_true, y_pred, alpha, is_logits, threads)
}

#' Fast C++ Temperature-Scaled Refinement for Multiclass Classification
#' @keywords internal
rcpp_compute_ts_refinement_multiclass <- function(y_true, y_pred, num_class, alpha = 1.0, is_logits = FALSE, threads = 1L) {
    .Call(`_evoFE_rcpp_compute_ts_refinement_multiclass`, y_true, y_pred, num_class, alpha, is_logits, threads)
}

#' Train RealMLP Model in C++
#'
#' @param x_train Numeric matrix of training features.
#' @param y_train Numeric vector of training targets.
#' @param x_val Optional numeric matrix of validation features.
#' @param y_val Optional numeric vector of validation targets.
#' @param task String: "regression", "classification", or "multiclass".
#' @param n_epochs Integer: number of training epochs (default 256).
#' @param batch_size Integer: batch size (default 256).
#' @param lr Numeric: base learning rate (<0 for tuned defaults).
#' @param early_stopping_rounds Integer: patience for early stopping (0 = disabled).
#' @param seed Integer: random seed.
#' @param verbose Integer: verbosity level (0 = silent, 1 = normal, 2 = detailed).
#' @param num_classes Integer: number of classes for multiclass task.
#' @param threads Integer: number of threads for parallel computation.
#' @param metric String: validation metric to optimize and report.
#' @param hidden_dim Integer: hidden layer dimension (default 256).
#' @return A List containing model weights, training statistics, and feature importances.
#' @export
rcpp_realmlp_train <- function(x_train, y_train, x_val = NULL, y_val = NULL, task = "regression", n_epochs = 256L, batch_size = 256L, lr = -1.0, early_stopping_rounds = 0L, seed = 42L, verbose = 0L, num_classes = 0L, threads = 1L, metric = "default", hidden_dim = 256L) {
    .Call(`_evoFE_rcpp_realmlp_train`, x_train, y_train, x_val, y_val, task, n_epochs, batch_size, lr, early_stopping_rounds, seed, verbose, num_classes, threads, metric, hidden_dim)
}

#' Predict with RealMLP Model in C++
#'
#' @param model_state List returned by `rcpp_realmlp_train`.
#' @param x_new Numeric matrix of new input features.
#' @return A NumericMatrix of predictions.
#' @export
rcpp_realmlp_predict <- function(model_state, x_new) {
    .Call(`_evoFE_rcpp_realmlp_predict`, model_state, x_new)
}

#' Fast C++ Row-wise Minimum
#' @keywords internal
rcpp_fused_row_min <- function(cols, threads = 1L) {
    .Call(`_evoFE_rcpp_fused_row_min`, cols, threads)
}

#' Fast C++ Row-wise Maximum
#' @keywords internal
rcpp_fused_row_max <- function(cols, threads = 1L) {
    .Call(`_evoFE_rcpp_fused_row_max`, cols, threads)
}

#' Fast C++ Geometric Mean
#' @keywords internal
rcpp_fused_geometric_mean <- function(cols, eps = 1e-6, threads = 1L) {
    .Call(`_evoFE_rcpp_fused_geometric_mean`, cols, eps, threads)
}

#' Fast C++ Harmonic Mean
#' @keywords internal
rcpp_fused_harmonic_mean <- function(cols, eps = 1e-6, threads = 1L) {
    .Call(`_evoFE_rcpp_fused_harmonic_mean`, cols, eps, threads)
}

#' Fast C++ Pythagorean Imbalance (AM - HM)
#' @keywords internal
rcpp_fused_pythagorean_imbalance <- function(cols, eps = 1e-6, threads = 1L) {
    .Call(`_evoFE_rcpp_fused_pythagorean_imbalance`, cols, eps, threads)
}

#' Fast C++ Relative Rating (Primary vs Mean of Others)
#' @keywords internal
rcpp_fused_relative_rating <- function(cols, threads = 1L) {
    .Call(`_evoFE_rcpp_fused_relative_rating`, cols, threads)
}

